use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};
use anyhow::Result;

/// Run all enabled cops, collect every diagnostic, then write `.rubric_todo.toml`
/// that suppresses each (cop, file) pair so that `rubric check` can be run in CI
/// without failing on pre-existing violations.
pub fn run(path: &Path, config: &crate::config::Config, rules: &[Box<dyn rubric_core::Rule + Send + Sync>]) -> Result<usize> {
    let root = if path.is_dir() {
        path.to_path_buf()
    } else {
        path.parent().unwrap_or(path).to_path_buf()
    };

    let files: Vec<PathBuf> = crate::runner::collect_ruby_files(path)
        .into_iter()
        .filter(|f| !crate::is_excluded(f, &root, &config.exclude))
        .collect();

    if files.is_empty() {
        println!("No Ruby files found.");
        return Ok(0);
    }

    let mut results = crate::runner::run_all_files(&files, rules);

    // Apply per-rule excludes (same as `check`)
    for (file, _source, diagnostics) in &mut results {
        diagnostics.retain(|d| {
            if let Some(rule_cfg) = config.rules.get(d.rule) {
                if !rule_cfg.exclude.is_empty()
                    && crate::is_excluded(file, &root, &rule_cfg.exclude)
                {
                    return false;
                }
            }
            true
        });
    }

    // Group: cop_name → sorted set of relative file paths
    let mut by_cop: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();
    for (file, _source, diagnostics) in &results {
        let rel = file.strip_prefix(&root).unwrap_or(file);
        let rel_str = rel.to_string_lossy().into_owned();
        for diag in diagnostics {
            by_cop
                .entry(diag.rule.to_string())
                .or_default()
                .insert(rel_str.clone());
        }
    }

    let total_cops = by_cop.len();
    let total_files: usize = by_cop.values().map(|s| s.len()).sum();

    let output_path = root.join(".rubric_todo.toml");
    let content = build_todo_toml(&by_cop);
    std::fs::write(&output_path, &content)?;

    println!(
        "Written {} — {} cop(s) suppressed across {} file(s).",
        output_path.display(),
        total_cops,
        total_files,
    );
    println!("Commit this file and run `rubric check` — it will now pass.");
    println!("Remove entries from .rubric_todo.toml as you fix violations.");

    Ok(total_cops)
}

/// Build the TOML content for `.rubric_todo.toml`.
fn build_todo_toml(by_cop: &BTreeMap<String, BTreeSet<String>>) -> String {
    let mut out = String::from("# Auto-generated by `rubric todo`. Commit this file.\n");
    out.push_str("# Remove entries as you fix violations; delete the file when it is empty.\n");

    if by_cop.is_empty() {
        out.push_str("\n# No violations found — nothing to suppress.\n");
        return out;
    }

    for (cop, files) in by_cop {
        out.push('\n');
        out.push_str(&format!("[todo.\"{}\"]\n", cop));
        out.push_str("files = [\n");
        for f in files {
            out.push_str(&format!("  \"{}\",\n", f));
        }
        out.push_str("]\n");
    }

    out
}

#[cfg(test)]
mod tests {
    use super::build_todo_toml;
    use std::collections::{BTreeMap, BTreeSet};

    #[test]
    fn empty_produces_no_violation_comment() {
        let map: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();
        let out = build_todo_toml(&map);
        assert!(out.contains("No violations found"));
        assert!(!out.contains("[todo."));
    }

    #[test]
    fn single_cop_single_file() {
        let mut map: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();
        map.entry("Style/Documentation".into())
            .or_default()
            .insert("lib/foo.rb".into());
        let out = build_todo_toml(&map);
        assert!(out.contains("[todo.\"Style/Documentation\"]"));
        assert!(out.contains("\"lib/foo.rb\""));
    }

    #[test]
    fn multiple_cops_sorted_alphabetically() {
        let mut map: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();
        map.entry("Style/Documentation".into())
            .or_default()
            .insert("lib/a.rb".into());
        map.entry("Layout/LineLength".into())
            .or_default()
            .insert("lib/b.rb".into());
        let out = build_todo_toml(&map);
        let layout_pos = out.find("Layout/LineLength").unwrap();
        let style_pos = out.find("Style/Documentation").unwrap();
        assert!(layout_pos < style_pos, "Layout cops should sort before Style cops");
    }

    #[test]
    fn files_within_cop_are_sorted() {
        let mut map: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();
        let set = map.entry("Lint/Foo".into()).or_default();
        set.insert("lib/z.rb".into());
        set.insert("lib/a.rb".into());
        let out = build_todo_toml(&map);
        let a_pos = out.find("lib/a.rb").unwrap();
        let z_pos = out.find("lib/z.rb").unwrap();
        assert!(a_pos < z_pos, "Files within a cop should be sorted");
    }
}
